name: Deploy

on:
  push:
    branches:
      main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest python-dotenv flask-cors PyJWT
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi 

    - name: Install missing dependencies
      run: |
        pip install Flask-SQLAlchemy SQLAlchemy Flask-Testing

rsync -avz --exclude 'node_modules' --exclude '.git' --exclude '.env' \
-e "ssh -i ~/Documents/SPM*SSH/brendan.pem" \
. ubuntu@ec2-52-204-255-212.compute-1.amazonaws.com:~/app
