name: Deploy

env:
    VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
    VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}


on:
  push:
    branches:
      main

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Vercel CLI
      run: npm install --global vercel

    - name: Pull Vercel Env Info
      run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN_ID }}

    - name: Build Project
      run: vercel build -- prod --token=${{ secrets.VERCEL_TOKEN_ID }}

    - name: Deploy Project
      run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN_ID }}




